name: python Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: pytest python/test_app.py -v 
  build-and-push:
    needs: test
    uses: ./.github/workflows/q7_deploy.yml
    with:
      image-name: ${{ secrets.DOCKERHUB_USERNAME }}/question7
      tag: latest
    secrets: inherit 

