name: lint
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run linting
        run: flake8 python/app.py

      - name: Run tests
        run: pytest python/test_app.py -v

  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: temp
          VERSION: ${{ github.sha }}
        run: |
          SHORT_SHA=$(echo $VERSION | cut -c1-8)

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:kaki-$SHORT_SHA ./python